server:
  port: ${SERVER_PORT:8080}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
jwt:
  header: Authorization
  token:
    prefix: "Bearer "
    access_validity: 600000
    refresh_validity: 3600000
  authorities_key: roles
  secret: 8d0430fbb7e52620bca66c47cb80c1a9b844e629195010f4c27643528ea021838812c9f6669f979fe7431ea210014737ca08a05e568d82eefecaab5624d163b9

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:postgresql://localhost:5432/kidspainting"
    username: admin
    password: admin
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

---

spring:
  config:
    activate:
      on-profile: heroku
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM}
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        "[globally_quoted_identifiers]": true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect